baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Euphria'

[params]
  author = "Euphria"
  description = "A cat who likes sleeping, eating, fishing, playing football, and all interesting things."
  menu_item_separator = "<br>"
  avatar = "mao.jpg"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    identifier = "cv"
    name = "My CV"
    url = "/cv.pdf"
    weight = 3

[[params.social]]
  icon = "brand-github"
  name = "My Github"
  url = "https://github.com/Euphria"
[[params.social]]
  icon = "brand-googlescholar"
  name = "Google Scholar"
  url = "https://scholar.google.com/citations?user=MFwagUQAAAAJ"
[[params.social]]
  icon = "mail"
  name = "Email"
  url = "mailto:euphria1222@gmail.com"

[params.style]
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"